# -*- coding: utf-8 -*-
"""Projeto1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHSceiMH1mbVGo92XLtnUJG1VCA4_x2k

Passo a passo:
* Passo 1: Importar a base de dados
* Passo 2: Calcular o faturamento de cada loja
* Passo 3: Calcular a quantidade de produtos vendidos de cada loja
* Passo 4: Calcular o Ticket Médio dos produtos de cada loja
* Passo 5: Enviar e-mail para diretoria
* Passo 6: Enviar e-mail para cada loja

Importando base de dados:
"""

import pandas as pd

tabela_vendas = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Vendas.xlsx")
display(tabela_vendas)

"""Calculando faturamento de cada loja:

1. Filtramos as variáveis que serão necessárias.
2. Agrupar lojas que são as mesmas e somar o valor final de cada uma delas.
3. Ordenar tabela a partir da variavel x, e decidir se vai ser ordem crescente(True) ou decrescente(False)
"""

tabela_faturamento = tabela_vendas[['ID Loja', 'Valor Final']].groupby("ID Loja").sum()
tabela_faturamento = tabela_faturamento.sort_values(by="Valor Final", ascending=True)
display(tabela_faturamento)

"""Calculando a quantidade de produtos vendidos de cada loja:

1. Filtramos as variáveis que serão necessárias.
2. Agrupar lojas que são as mesmas e somar o valor final de cada uma delas.
3. Ordenar tabela a partir da variavel x, e decidir se vai ser ordem crescente(True) ou decrescente(False)
"""

tabela_quantidade = tabela_vendas[['ID Loja', 'Quantidade']].groupby("ID Loja").sum()
tabela_quantidade = tabela_quantidade.sort_values(by="Quantidade", ascending=True)
display(tabela_quantidade)

"""Calculando o Ticket Médio dos produtos de cada loja.
Ticket médio é o faturamento / quantidade.
O abre e fecha parenteses + o .to_frame() é para transformar em dataframe (tabela).
Renomear coluna do ticket medio que ficou como 0.

"""

ticket_medio = (tabela_faturamento["Valor Final"] / tabela_quantidade["Quantidade"]).to_frame()
ticket_medio = ticket_medio.rename(columns={0: "Ticket Médio"})
display(ticket_medio)

"""Enviando e-mail para diretória:
1. Criar/definir uma função, passando seus parametros/argumentos/variável.
2. Quando for enviar algo que não seja texto, acrescentar um f no inicio e a variável deve estar entre {}.
3. Para escrever deve-se iniciar com <*p> e finalizar com <*/p>.
4. Para a tabela ficar legal, deve colocar {tabela.to_html()}.
"""

import smtplib
import email.message

def enviar_email(nome_da_loja, tabela):

  server = smtplib.SMTP('smtp.gmail.com:587')
  corpo_email = f"""
  <p>Prezados,</p>
  <p>Segue relatório de vendas </p>
  {tabela.to_html()}
  <p>Qualquer dúvida estou à disposição</p>
  """

  msg = email.message.Message()
  msg['Subject'] = f"Relatório de Vendas - {nome_da_loja}" #editado

# Fazer antes (apenas na 1ª vez): Ativar Aplicativos não Seguros.
  # Gerenciar Conta Google -> Segurança -> Aplicativos não Seguros -> Habilitar
# Caso mesmo assim dê o erro: smtplib.SMTPAuthenticationError: (534,
# Você faz o login no seu e-mail e depois entra em: https://accounts.google.com/DisplayUnlockCaptcha
  msg['From'] = 'escr.tatianeximenes@gmail.com'
  msg['To'] = 'ximenes_taty@hotmail.com'
  password = 'T3a...123*' #editar e fazer a configuração no email para liberar
  msg.add_header('Content-Type', 'text/html')
  msg.set_payload(corpo_email )

  s = smtplib.SMTP('smtp.gmail.com: 587')
  s.starttls()
# Login Credentials for sending the mail
  s.login(msg['From'], password)
  s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
  print('Email enviado')

enviar_email("Diretoria", tabela_faturamento) #enviar tabela de faturamento para diretoria

"""Criar tabela completa para enviar a diretória"""

tabela_completa = tabela_faturamento.join(tabela_quantidade).join(ticket_medio)
enviar_email("Diretoria", tabela_completa)
#display(tabela_completa)

"""Enviando e-mail para cada loja"""

lista_lojas = tabela_vendas["ID Loja"].unique()

for loja in lista_lojas:
  tabela_loja = tabela_vendas.loc[tabela_vendas["ID Loja"] == loja, ["ID Loja", "Quantidade", "Valor Final"]] #filtar linha e coluna
  tabela_loja = tabela_loja.groupby("ID Loja").sum()

  tabela_loja["Ticker Medio"] = tabela_loja["Valor Final"] / tabela_loja["Quantidade"]
  enviar_email(loja, tabela_loja)

#display(tabela_loja)