# -*- coding: utf-8 -*-
"""Lista10_BES038.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dqVyRuvsKsKiZto9qW36HnGJI8x90TNq
"""

#Bibioteca
!pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

#  antecedente / variaveis linguisticas
qualidade = ctrl.Antecedent(np.arange(0, 11, 1), 'qualidade')
servico = ctrl.Antecedent(np.arange(0, 11, 1), 'servico')
gorjeta = ctrl.Consequent(np.arange(0, 26, 1), 'gorjeta')

# função de pertinência (3, 5, or 7)
qualidade.automf(3, names=['ruim','boa','saborosa'])
servico.automf(3, names=['ruim','aceitável','ótimo'])
#servico.automf(3)

"""Altere as funções de pertinência do consequente (Gorjeta) para:"""

gorjeta['baixa'] = fuzz.sigmf(gorjeta.universe, 5, -1)
gorjeta['media'] = fuzz.gaussmf(gorjeta.universe, 10, 3)
gorjeta['alta'] = fuzz.pimf(gorjeta.universe, 10, 20, 25, 50)

#a. visualize o conjunto gorjeta com gorjeta.view()
#qualidade['boa'].view()
qualidade.view()
servico.view()
gorjeta.view()

#b. altere a taxa da qualidade para 0.5 e serviço 0.5
qualidade = ctrl.Antecedent(np.arange(0, 0.5, 1), 'qualidade')
servico = ctrl.Antecedent(np.arange(0, 0.5, 1), 'servico')

#c. imprima o resultado e visualize o resultado no conjunto fuzzy gorjeta
qualidade.view()
servico.view()
gorjeta.view()