# -*- coding: utf-8 -*-
"""enem_1998.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugfNoTkarZrdkliash3h6Ysvj41Nc1wh

# **Trabalhando** com dask (pela primeira vez)

- https://docs.dask.org/en/latest/dataframe-parquet.html
- https://www.analyticsvidhya.com/blog/2018/08/dask-big-datasets-machine_learning-python/
- https://www.youtube.com/watch?v=WLBEzlwvCp4
"""

!pip install "dask[complete]"

import dask
import dask.dataframe as dd

import numpy as np
import pandas as pd

path = '/content/MICRODADOS_ENEM_1998.csv'

# assume_missing=True, permite que o Dask lide corretamente com dados contendo valores faltantes em colunas que, de outra forma, seriam considerados exclusivamente numéricos.
df = dd.read_csv(path, assume_missing = True, sep = ';')
df.head()

print('Quantidade de linhas: ', len(df))
print('Quantidade de colunas: ', len(df.columns)) #df.shape[0].compute()
#df.info() #mostra quantas colunas existem, qual é a primeira e qual é a última, além do count dos tipos dessas colunas

list(df.columns)

df.describe().compute()

"""### Seleção das variáveis e seus preenchimentos"""

#filtro de variáveis
df_subset = df[['NU_ANO','TP_FAIXA_ETARIA','TP_SEXO', 'SG_UF_RESIDENCIA','TP_PRESENCA','CO_PROVA','NU_NOTA_OBJETIVA','TP_STATUS_REDACAO','NU_NOTA_REDACAO','IN_QSE', 'Q2', 'Q4', 'Q5', 'Q6', 'Q7', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13', 'Q17', 'Q18', 'Q22', 'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q68', 'Q69', 'Q70', 'Q71', 'Q72', 'Q73', 'Q74', 'Q75', 'Q76', 'Q97', 'Q98', 'Q114', 'Q116', 'Q118', 'Q119', 'Q120', 'Q121', 'Q122', 'Q123', 'Q124', 'Q125', 'Q126', 'Q127', 'Q128', 'Q129', 'Q130', 'Q131', 'Q132', 'Q134', 'Q135', 'Q136']]

print('Quantidade de linhas: ', len(df_subset))
print('Quantidade de colunas: ', len(df_subset.columns)) #df_subset.shape[0].compute()

df_subset.compute()

# Renomeando vairáveis
df_renomeado = df_subset.rename(columns={'IN_QSE': 'RESP_QUEST_SOCIO',
                                  'Q2': 'ANO_NASC',
                                  'Q4': 'RACA_COR',
                                  'Q5': 'ESTADO_CIVIL',
                                  'Q6': 'CQUEM_MORA',
                                  'Q7': 'QTD_PESSOAS_DOMICILIO',
                                  'Q9': 'QTD_FILHOS',
                                  'Q10': 'ESC_PAI',
                                  'Q11': 'PROF_PAI',
                                  'Q12': 'ESC_MAE',
                                  'Q13': 'PROF_MAE',
                                  'Q17': 'MOD_CONCL_ENS_FUND',
                                  'Q18': 'ANO_CONCL_ENS_MEDIO',
                                  'Q22': 'TIPO_ESC_ENS_MEDIO',
                                  'Q25': 'LINGUA_ESTR',
                                  'Q26': 'COMP_INFOR',
                                  'Q27': 'INS_MUSIC',
                                  'Q28': 'GINASTICA',
                                  'Q29': 'ART_PLAST',
                                  'Q68': 'AMG_DROGAS',
                                  'Q69': 'ACOMP_POLITICA',
                                  'Q70': 'ACOMP_ESPORTES',
                                  'Q71': 'ACOMP_ECONOMIA',
                                  'Q72': 'ACOMP_MODAS',
                                  'Q73': 'ACOMP_CULTURAS',
                                  'Q74': 'ACOMP_COMP_SEXUAL',
                                  'Q75': 'ACOMP_MEIO_AMBIENTE',
                                  'Q76': 'INT_SOCIAIS',
                                  'Q97': 'TRAB_ATUALMENTE',
                                  'Q98': 'RENDA_MENSAL',
                                  'Q114': 'QUAL_ATIVIDADE',
                                  'Q116': 'TEMPO_TRABALHO',
                                  'Q118': 'MOTIVO_NAO_TRAB',
                                  'Q119': 'PART_SUST_FAM',
                                  'Q120': 'RENDA_TOTAL_MENSAL',
                                  'Q121': 'AUTOMOVEL',
                                  'Q122': 'TV_CORES',
                                  'Q123': 'MICROCOMPUTADOR',
                                  'Q124': 'VIDEOCASSETE',
                                  'Q125': 'MAQ_LAVAR_ROUPA',
                                  'Q126': 'ASPIRADOR_PO',
                                  'Q127': 'GELADEIRA',
                                  'Q128': 'FREEZER',
                                  'Q129': 'CASA_PROPRIA',
                                  'Q130': 'EMPREGADA',
                                  'Q131': 'BICILETA',
                                  'Q132': 'MOTOCICLETA',
                                  'Q134': 'INST_MUSICAL',
                                  'Q135': 'MESA_ESTUDOS',
                                  'Q136': 'CALCULADORA'})

# Renomeando o conteúdo
mapeamentos = {
    'TP_FAIXA_ETARIA': {          # coluna → {código: rótulo}
        '1': 'Menos de 17 anos',
        '2': '17 anos',
        '3': '18 anos',
        '4': '19 anos',
        '5': '20 anos',
        '6': '21 anos',
        '7': '22 anos',
        '8': '23 anos',
        '9': '24 anos',
        '10': '25 anos',
        '11': 'Entre 26 e 30 anos',
        '12': 'Entre 31 e 35 anos',
        '13': 'Entre 36 e 40 anos',
        '14': 'Entre 41 e 45 anos',
        '15': 'Entre 46 e 50 anos',
        '16': 'Entre 51 e 55 anos',
        '17': 'Entre 56 e 60 anos',
        '18': 'Entre 61 e 65 anos',
        '19': 'Entre 66 e 70 anos',
        '20': 'Maior de 70 anos'
    },
    'CO_PROVA': {
        'A': 'Amarela',
        'B': 'Branca',
        'G': 'Grafite',
        'Z': 'Azul'
    },
    'TP_PRESENCA': {
        '0': 'Faltou',
        '1': 'Presente'
    },
    'TP_STATUS_REDACAO': {
        'F': 'Faltou',
        'P': 'Presente'
    },
    'RESP_QUEST_SOCIO': {
        '0': 'Não respondeu',
        '1': 'Respondeu'
    },
    'ANO_NASC': {
        'A': 'Após 1981',
        'B': '1981',
        'C': '1980',
        'D': '1979',
        'E': '1978',
        'F': '1977',
        'G': 'Entre 1973 e 1976',
        'H': 'Antes de 1973'
    },
    'RACA_COR': {
        'A': 'Branco',
        'B': 'Pardo',
        'C': 'Negro',
        'D': 'Amarelo',
        'E': 'Indigena'
    },
    'ESTADO_CIVIL' : {
        'A': 'Solteiro',
        'B': 'Casado/mora com companheiro(a)',
        'C': 'Separado/Divorciado/Desquitado',
        'D': 'Viúvo'
    },
    'CQUEM_MORA' : {
        'A': 'Com o pai e a mãe',
        'B': 'Só com o pai',
        'C': 'Só com a mãe',
        'D': 'Com parentes/amigos',
        'E': 'Com pai e mãe em nova união',
        'F': 'Sozinho',
        'G': 'Outra situação'
    },
    'QTD_PESSOAS_DOMICILIO' : {
        'A': 'Uma pessoa',
        'B': 'Duas pessoas',
        'C': 'Três pessoas',
        'D': 'Quatro pessoas',
        'E': 'Cinco pessoas',
        'F': 'Seis pessoas',
        'G': 'Mais de seis pessoas'
    },
    'QTD_FILHOS': {
        'A': 'Não tenho filhos',
        'B': 'Um filho',
        'C': 'Dois filhos',
        'D': 'Três filhos',
        'E': 'Quatro ou mais filhos'
    },
    'ESC_PAI' : {
        'A': 'Nunca frequentou a escola',
        'B': 'Da primeira à quarta série do ensino fundamental (antigo primário)',
        'C': 'Da quinta à oitava série do ensino fundamental (antigo ginásio)',
        'D': 'Ensino Médio (2º grau) incompleto',
        'E': 'Ensino Médio (2º grau) completo',
        'F': 'Ensino Superior incompleto',
        'G': 'Ensino Superior completo',
        'H': 'Pós-graduação'
    },
    'PROF_PAI' : {
        'A': 'Trabalhadora do setor de produção industrial (com registro ou carteira assinada)',
        'B': 'Trabalhadora do setor primário/agricultura/pecuária/pesca (com registro ou carteira assinada)',
        'C': 'Trabalhadora do setor de prestação de serviços/comércio/banco/transporte, etc. (com registro ou carteira assinada)',
        'D': 'Funcionária do setor público',
        'E': 'Gerente, administradora ou diretora de empresa privada',
        'F': 'Trabalha no próprio negócio/empresa ou comércio próprio',
        'G': 'Profissional liberal, professor, técnico de nível superior',
        'H': 'Trabalhador do setor informal (sem carteira assinada)',
        'I': 'Desempregado',
        'J': 'Aposentado',
        'L': 'Não sei'
    },
    'ESC_MAE' : {
        'A': 'Nunca frequentou a escola',
        'B': 'Da primeira à quarta série do ensino fundamental (antigo primário)',
        'C': 'Da quinta à oitava série do ensino fundamental (antigo ginásio)',
        'D': 'Ensino Médio (2º grau) incompleto',
        'E': 'Ensino Médio (2º grau) completo',
        'F': 'Ensino Superior incompleto',
        'G': 'Ensino Superior completo',
        'H': 'Pós-graduação'
    },
    'PROF_MAE' : {
        'A': 'Trabalhadora do setor de produção industrial (com registro ou carteira assinada)',
        'B': 'Trabalhadora do setor primário/agricultura/pecuária/pesca (com registro ou carteira assinada)',
        'C': 'Trabalhadora do setor de prestação de serviços/comércio/banco/transporte, etc. (com registro ou carteira assinada)',
        'D': 'Funcionária do setor público',
        'E': 'Gerente, administradora ou diretora de empresa privada',
        'F': 'Trabalha no próprio negócio/empresa ou comércio próprio',
        'G': 'Profissional liberal, professora, técnico de nível superior',
        'H': 'Trabalhadora do setor informal (sem carteira assinada)',
        'I': 'Desempregada',
        'J': 'Aposentada',
        'L': 'Dona de casa',
        'M': 'Não sei'
    },
    'MOD_CONCL_ENS_FUND' : {
        'A': 'Ensino regular',
        'B': 'Ensino supletivo'
    },
    'ANO_CONCL_ENS_MEDIO' : {
        'A': 'Vou concluí-lo no segundo semestre de 1998',
        'B': 'Concluí-o no primeiro semestre de 1998',
        'C': 'Concluí-o em 1997',
        'D': 'Concluí-o em 1996',
        'E': 'Concluí-o em 1995',
        'F': 'Concluí-o entre 1991 e 1994',
        'G': 'Concluí-o antes de 1991'
    },
    'TIPO_ESC_ENS_MEDIO' : {
        'A': 'Federal',
        'B': 'Estadual',
        'C': 'Municipal',
        'D': 'Particular'
    },
    'LINGUA_ESTR' : {
        'A': 'Sim',
        'B': 'Não'
    },
    'COMP_INFOR' : {
        'A': 'Sim',
        'B': 'Não'
    },
    'INS_MUSIC' : {
        'A': 'Sim',
        'B': 'Não'
    },
    'GINASTICA' : {
        'A': 'Sim',
        'B': 'Não'
    },
    'ART_PLAST' : {
        'A': 'Sim',
        'B': 'Não'
    },
    'AMG_DROGAS' : {
        'A': 'Sim, amigos próximos',
        'B': 'Sim, amigos distantes',
        'C': 'Não'
    },
    'ACOMP_POLITICA' : {
        'A': 'Sim, muito',
        'B': 'Sim, mais ou menos',
        'C': 'Só um pouco',
        'D': 'Não, não me interesso'
    },
    'ACOMP_ESPORTES' : {
        'A': 'Sim, muito',
        'B': 'Sim, mais ou menos',
        'C': 'Só um pouco',
        'D': 'Não, não me interesso'
    },
    'ACOMP_ECONOMIA' : {
        'A': 'Sim, muito',
        'B': 'Sim, mais ou menos',
        'C': 'Só um pouco',
        'D': 'Não, não me interesso'
    },
    'ACOMP_MODAS' : {
        'A': 'Sim, muito',
        'B': 'Sim, mais ou menos',
        'C': 'Só um pouco',
        'D': 'Não, não me interesso'
    },
    'ACOMP_CULTURAS' : {
        'A': 'Sim, muito',
        'B': 'Sim, mais ou menos',
        'C': 'Só um pouco',
        'D': 'Não, não me interesso'
    },
    'ACOMP_COMP_SEXUAL' : {
        'A': 'Sim, muito',
        'B': 'Sim, mais ou menos',
        'C': 'Só um pouco',
        'D': 'Não, não me interesso'
    },
    'ACOMP_MEIO_AMBIENTE' : {
        'A': 'Sim, muito',
        'B': 'Sim, mais ou menos',
        'C': 'Só um pouco',
        'D': 'Não, não me interesso'
    },
    'INT_SOCIAIS' : {
        'A': 'Sim, muito',
        'B': 'Sim, mais ou menos',
        'C': 'Só um pouco',
        'D': 'Não, não me interesso'
    },
    'TRAB_ATUALMENTE' : {
        'A': 'Sim',
        'B': 'Não'
    },
    'RENDA_MENSAL' : {
        'A': 'Até 1 salário mínimo (até R$130,00)',
        'B': 'Entre 1 e 2 salários mínimos (entre R$131,00 e R$260,00)',
        'C': 'De 2 a 5 salários mínimos (de R$261,00 a R$650,00)',
        'D': 'De 5 a 10 salário mínimos (de R$651,00 a R$1.300,00)',
        'E': 'De 10 a 30 salários mínimos (de R$1.301,00 a R$3.900,00)',
        'F': 'De 30 a 50 salários mínimos (de R$3.901,00 a R$6.500,00)',
        'G': 'Mais de 50 salários mínimos (mais de R$6.500,00)'
    },
    'QUAL_ATIVIDADE' : {
        'A': 'Trabalhador do setor de produção industrial',
        'B': 'Trabalhador do setor primário/agricultura/pecuária/pesca',
        'C': 'Trabalhador do setor de prestação de serviços/comércio/banco/transporte',
        'D': 'Funcionário do setor público',
        'E': 'Gerente, administrador ou diretor de empresa privada',
        'F': 'Trabalha no próprio negócio/empresa ou comércio próprio',
        'G': 'Profissional liberal, professor, técnico de nível superior',
        'H': 'Trabalhador do setor informal (sem carteira assinada)'
    },
    'TEMPO_TRABALHO' : {
        'A': 'Menos de 1 ano',
        'B': 'Entre 1 e 2 anos',
        'C': 'Entre 2 e 4 anos',
        'D': 'Mais de 4 anos'
    },
    'MOTIVO_NAO_TRAB' : {
        'A': 'Não preciso trabalhar',
        'B': 'Estava trabalhando, mas estou desempregado(a)',
        'C': 'Não consigo encontrar um trabalho na minha ocupação',
        'D': 'Estou estudando'
    },
    'PART_SUST_FAM' : {
        'A': 'Sim, com todo o meu rendimento',
        'B': 'Sim, com parte do meu rendimento',
        'C': 'Não, tenho família, mas meus rendimentos são para meu próprio uso',
        'D': 'Não tenho rendimentos',
        'E': 'Não tenho família/meus rendimentos são só para meu próprio uso'
    },
    'RENDA_TOTAL_MENSAL' : {
        'A': 'Até 1 salário mínimo (até R$130,00)',
        'B': 'Entre 1 e 2 salários mínimos (entre R$131,00 e R$260,00)',
        'C': 'De 2 a 5 salários mínimos (de R$261,00 a R$650,00)',
        'D': 'De 5 a 10 salário mínimos (de R$651,00 a R$1.300,00)',
        'E': 'De 10 a 30 salários mínimos (de R$1.301,00 a R$3.900,00)',
        'F': 'De 30 a 50 salários mínimos (de R$3.901,00 a R$6.500,00)',
        'G': 'Mais de 50 salários mínimos (mais de R$6.500,00)',
        'H': 'Não sabe'
    },
    'AUTOMOVEL' : {

        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
    'TV_CORES' : {
        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
    'MICROCOMPUTADOR' : {
        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
    'VIDEOCASSETE' : {
        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
     'MAQ_LAVAR_ROUPA' : {
        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
    'ASPIRADOR_PO' : {
        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
    'GELADEIRA' : {
        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
    'FREEZER' : {
        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
     'CASA_PROPRIA' : {
        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
    'EMPREGADA' : {
        'A': 'Não tem',
        'B': '1',
        'C': '2',
        'D': '3 ou mais'
    },
    'BICILETA' : {
        'A': 'Sim',
        'B': 'Não',
        'C': 'Não, mas pretendo ter num futuro próximo'
    },
    'MOTOCICLETA' : {
        'A': 'Sim',
        'B': 'Não',
        'C': 'Não, mas pretendo ter num futuro próximo'
    },
    'INST_MUSICAL' : {
        'A': 'Sim',
        'B': 'Não',
        'C': 'Não, mas pretendo ter num futuro próximo'
    },
     'MESA_ESTUDOS' : {
        'A': 'Sim',
        'B': 'Não',
        'C': 'Não, mas pretendo ter num futuro próximo'
    },
    'CALCULADORA' : {
        'A': 'Sim',
        'B': 'Não',
        'C': 'Não, mas pretendo ter num futuro próximo'
    }
}

tipos = {
    'NU_ANO'                    : 'int64', # numérico inteiro
    'TP_FAIXA_ETARIA'           : 'category',        # mantém dicionário‑encoding eficiente
    'TP_SEXO'                   : 'category',
    'CO_PROVA'                  : 'category',
    'TP_PRESENCA'               : 'category',
    'CO_PROVA'                  : 'category',
    'TP_STATUS_REDACAO'         : 'category',
    'RESP_QUEST_SOCIO'          : 'category',
    'ANO_NASC'                  : 'category',
    'RACA_COR'                  : 'category',
    'ESTADO_CIVIL'              : 'category',
    'CQUEM_MORA'                : 'category',
    'QTD_PESSOAS_DOMICILIO'     : 'category',
    'QTD_FILHOS'                : 'category',
    'ESC_PAI'                   : 'category',
    'PROF_PAI'                  : 'category',
    'ESC_MAE'                   : 'category',
    'PROF_MAE'                  : 'category',
    'MOD_CONCL_ENS_FUND'        : 'category',
    'ANO_CONCL_ENS_MEDIO'       : 'category',
    'TIPO_ESC_ENS_MEDIO'        : 'category',
    'LINGUA_ESTR'               : 'category',
    'COMP_INFOR'                : 'category',
    'INS_MUSIC'                 : 'category',
    'GINASTICA'                 : 'category',
    'ART_PLAST'                 : 'category',
    'AMG_DROGAS'                : 'category',
    'ACOMP_POLITICA'            : 'category',
    'ACOMP_ESPORTES'            : 'category',
    'ACOMP_ECONOMIA'            : 'category',
    'ACOMP_MODAS'               : 'category',
    'ACOMP_CULTURAS'            : 'category',
    'ACOMP_COMP_SEXUAL'         : 'category',
    'ACOMP_MEIO_AMBIENTE'       : 'category',
    'INT_SOCIAIS'               : 'category',
    'TRAB_ATUALMENTE'           : 'category',
    'RENDA_MENSAL'              : 'category',
    'QUAL_ATIVIDADE'            : 'category',
    'TEMPO_TRABALHO'            : 'category',
    'MOTIVO_NAO_TRAB'           : 'category',
    'PART_SUST_FAM'             : 'category',
    'RENDA_TOTAL_MENSAL'        : 'category',
    'AUTOMOVEL'                 : 'category',
    'TV_CORES'                  : 'category',
    'MICROCOMPUTADOR'           : 'category',
    'VIDEOCASSETE'              : 'category',
    'MAQ_LAVAR_ROUPA'           : 'category',
    'ASPIRADOR_PO'              : 'category',
    'GELADEIRA'                 : 'category',
    'FREEZER'                   : 'category',
    'CASA_PROPRIA'              : 'category',
    'EMPREGADA'                 : 'category',
    'BICILETA'                  : 'category',
    'MOTOCICLETA'               : 'category',
    'INST_MUSICAL'              : 'category',
    'MESA_ESTUDOS'              : 'category',
    'CALCULADORA'               : 'category'
}

df_padronizado = df_renomeado.replace(mapeamentos)

# filtra os tipos para remover as colunas que são datas (cujo tipo é 'datetime64[ns]' ou 'datetime64[ns, UTC])'.
# cria um novo dicionário chamado numeros_e_cats com apenas os tipos numéricos e categóricos
numeros_e_cats = {k: v for k, v in tipos.items()
                  if v not in ('datetime64[ns]', 'datetime64[ns, UTC]')}

# Aplicar conversão de tipo em lote
df_padronizado = df_padronizado.astype(numeros_e_cats)

print(df_padronizado.dtypes)

for col in df_padronizado.columns:
    resultado = df_padronizado.groupby(col).size().compute()
    print(resultado)

"""### Escrita da base"""

df_padronizado.to_parquet(
    'enem_1998/',
    engine='pyarrow',           # recomendado
    compression='snappy',       # rápido e eficiente
    write_index=False           # geralmente desnecessário em cargas
)

# df.to_csv("enem_1998.csv", single_file=True, index=False) #Escrita em csv

"""### Validação - escrita"""

df_parquet = dd.read_parquet('/content/enem_1998/part.0.parquet', assume_missing = True)

print('Quantidade de linhas: ', len(df_parquet))
print('Quantidade de colunas: ', len(df_parquet.columns)) #df_parquet.shape[0].compute()

print(df_parquet.dtypes)

for col in df_parquet.columns:
    resultado = df_parquet.groupby(col).size().compute()
    print(resultado)

"""### Tentando escrever novamente a base com todas em String para o BigQuery"""

for col in df_padronizado.columns:
    df_padronizado[col] = df_padronizado[col].astype(str)

print(df_padronizado.dtypes)

for col in df_padronizado.columns:
    resultado = df_padronizado.groupby(col).size().compute()
    print(resultado)

df_padronizado.to_parquet(
    'enem_1998_new/',
    engine='pyarrow',           # recomendado
    compression='snappy',       # rápido e eficiente
    write_index=False           # geralmente desnecessário em cargas
)

# df.to_csv("enem_1998.csv", single_file=True, index=False) #Escrita em csv

