# -*- coding: utf-8 -*-
"""TABD - Andre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyr_VslXvVyzFvewEuZPE7oCwpCbC_TQ
"""

pip install pyspark

import pyspark
from pyspark.sql.functions import trim, to_date, year, month
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

#Leitura da base
df_exame = spark.read.csv('./sample_data/exame.csv', header= True)

#Leitura da base
df_atestado = spark.read.csv('./sample_data/atestado.csv', header= True)

#Leitura da base
df_empresa = spark.read.csv('./sample_data/empresa.csv', header= True)

#Leitura da base
df_funcionario = spark.read.csv('./sample_data/funcionario.csv', header= True)

#Leitura da base
df_medico = spark.read.csv('./sample_data/medico.csv', header= True)

#Leitura da base
df_tipoExame = spark.read.csv('./sample_data/tipoExame.csv', header= True)

"""**Quantidade de pacientes de uma empresa que são atendidos pelo médico X**
- CNPJ da empresa: 80699840108863
- Médico escolhido (crm): 961013
"""

teste_medico = df_medico.filter(F.col('crm') == "961013")

teste_empresa = df_funcionario.filter(F.col('cnpj_empresa') == '80699840108863')

teste_exame = df_exame.filter(F.col('crm_medico') == "961013")

teste_funcionario = df_empresa.filter(F.col("cnpj") == '80699840108863')

cond = [teste_empresa.cnpj_empresa == teste_funcionario.cnpj]

paciente_join_empresa = df_funcionario.join(df_empresa, cond, "inner")

paciente_join_empresa.show()

teste_medico = df_medico.filter(F.col('crm') == '961013')

teste_exame = df_exame.filter(F.col('crm_medico') == '961013')

cond2 = [teste_medico.crm == teste_exame.crm_medico]

medico_join_exame = df_exame.join(df_medico, cond2, "inner")

medico_join_exame.show()

cond3 = [paciente_join_empresa.cpf == medico_join_exame.cpf_funcionario]

qtd_pac_medico = medico_join_exame.join(paciente_join_empresa, cond3, "inner")

qtd_pac_medico.count()

qtd_pac_medico.show()

"""**Tipo de exame mais feito por determinada empresa**
- Empresa (cnpj): 80699840108863
"""

cond4 = [paciente_join_empresa.cpf == df_exame.cpf_funcionario]

tipo_exame = paciente_join_empresa.join(df_exame, cond, "inner")

tipo_exame.show()

tipo_exame.groupby('id_tipo_exame').count().show()