# -*- coding: utf-8 -*-
"""BES038 - Pre-processamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116rSKg2H7rScl2NfPSsy3J5tunlUN2tZ
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from google.colab import drive
drive.mount('/content/drive')

import numpy as np

"""1) Criar um script para realizar a Transformação Binária do atributo 'cargo' da base de dados fake_data_2.csv e mostrar a base de dados modificada."""

base_path = ("/content/drive/My Drive/inteligencia_artificial/fake_data_2.csv")
df = pd.read_csv(base_path)

df.head()

df = pd.get_dummies(df, columns = ['cargo'])
print(df)

"""2) Criar um script para converter os dados abaixo para valores numéricos e normalizá-los em [0, 1] e mostrar os resultado da base modificada."""

base_path = ("/content/drive/My Drive/inteligencia_artificial/ia_numerico.csv")
df_numerico = pd.read_csv(base_path)



"""3) Criar um scipt para realizar as normalizações: MinMax, Valor Máximo e por Desvio Padrão dos dados abaixo. Mostre o antes e o depois."""

base_path = ("/content/drive/My Drive/inteligencia_artificial/ia_cpf.csv")
df_cpf = pd.read_csv(base_path)

df_cpf.head()

#MinMax
norm_min_max = df_cpf.copy()
for column in norm_min_max.columns:
    norm_min_max[column] = (norm_min_max[column] - norm_min_max[column].min()) / (norm_min_max[column].max() - norm_min_max[column].min())
print(norm_min_max)

#Valor máximo
norm_max = df_cpf.copy()
for column in norm_max.columns:
    norm_max[column] = norm_max[column]  / norm_max[column].max()

display(norm_max)

#Desvio Padrão
print("Média:", np.mean(df_cpf.despesa))

print("Desvio padrão:", np.std(df_cpf.despesa))

"""4) Tratar os dados ausentes da base de dados iris_alterado:"""

base_path = ("/content/drive/My Drive/inteligencia_artificial/iris_alterado.csv")
df_iris = pd.read_csv(base_path)

#a)Criar um script para remover os atributos com dados ausentes
df_iris.dropna(axis='columns', inplace=True)
print(df_iris)

#b) Criar um script para remover as amostras com dados ausentes
df_iris.dropna(axis=0, inplace=True)
print(df_iris)

#c) Criar um script para inserir valores nos dados ausentes
valores_ausentes = df_iris.isnull()
medias = df_iris.mean()
df_iris.fillna(medias, inplace=True)
print(df_iris)

#d) Criar um script para remover as amostras duplicadas
df_iris.drop_duplicates(inplace=True)
print(df_iris)

