# -*- coding: utf-8 -*-
"""BSE038 - IA Lista 8 - RNA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfRZ_lVFuM_WvQSZ_tH4D1goAgDhVA0x

## **1) Criar um classificador Perceptron para classificar a base de dados Digitis da sklearn.**
"""

#a)
from sklearn import datasets
df = datasets.load_digits()

#b) Importe o método Perceptron de sklearn.linear_model
from sklearn.linear_model import Perceptron

X = df.data
y = df.target

#c) Treine a sua rede Perceptron com o método fit

clf = Perceptron(tol=1e-3, random_state=0, max_iter=1000)
clf.fit(X, y)
clf.score(X, y)
y_pred = clf.predict(X)

#d) Mostrar o resultado da métrica Acurácia (Score)
print(clf.score(X, y))

#e) Mostre a matriz de confusão
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y , y_pred))

"""## **2- Criar um classificador MLP a partir da base de dados PlayTennis.csv**"""

from google.colab import files
uploaded = files.upload()

#a) Converter os dados abaixo para valores numéricos.
PATH = '/content/PlayTennis.csv'
df_tennis = pd.read_csv(PATH)

from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
objList = df_tennis.select_dtypes(include = "object").columns

for obj in objList:
    df_tennis[obj] = lb.fit_transform(df_tennis[obj].astype(str))

# for var in df_tennis.columns:
#   label_encoder = LabelEncoder()
#   labels = label_encoder.fit_transform(df_tennis.var)

df_tennis.head()

#b) Utilize o classificador MLP (MLPClassifier)

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(alpha=1e-05, tol=1e-4, random_state=0, max_iter=10000)

#c) Altere os parâmetros da MLP, exemplo: max_iter,  alpha, tol)
clf = MLPClassifier(alpha=1e-03, tol=1e-2, random_state=0, max_iter=9000)

#d) Treine a sua rede MLP com o método fit
X = df.data
y = df.target

clf = Perceptron(tol=1e-3, random_state=0, max_iter=1000)
clf.fit(X, y)
clf.score(X, y)
y_pred = clf.predict(X)

clf = MLPClassifier(alpha=1e-03, tol=1e-2, random_state=0, max_iter=9000)

#e) Mostrar o resultado da métrica Acurácia (Score)
print(clf.score(X, y))

#f) Mostre a matriz de confusão
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y , y_pred))

"""## **3- Criar um classificar a partir de dados aleatórios**"""

#a) utilize o método make_classification para gerar uma base de dados exemplo:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=200, n_features=4)

#b) Utilize o classificador MLP (MLPClassifier)
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(alpha=1e-05, tol=1e-4, random_state=0, max_iter=10000)

#c) Altere os parâmetros da MLP, exemplo: max_iter,  alpha, tol)
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(alpha=1e-03, tol=1e-3, random_state=0, max_iter=8000)

#d) Treine a sua rede MLP com o método fit
X = df.data
y = df.target

clf = Perceptron(tol=1e-3, random_state=0, max_iter=1000)
clf.fit(X, y)
clf.score(X, y)
y_pred = clf.predict(X)

#e) Mostrar o resultado da métrica Acurácia (Score)
print(clf.score(X, y))

#f) Mostre a matriz de confusão
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y , y_pred))