# -*- coding: utf-8 -*-
"""BES038 - IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKE4xmsLdNBeSiTyunzRJMy4Gy0FuDT0
"""

import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
dt = load_iris()
print(list(dt.target_names))
print(dt.data.shape)
print(dt.feature_names)
print(dt['data'][:5])

"""1. Baixar a base de dados digits da ferramenta scikit-learn"""

from sklearn.datasets import load_digits
import pandas as pd
digits = load_digits()

print(digits.feature_names) #tributos/colunas
print(digits.data.shape) # quantidade de registros e colunas
print(digits['data'][:10]) #Listar as 10 primeiras amostras

"""2. Baixar a base de dados wine da ferramenta scikit-learn"""

from sklearn.datasets import load_wine
import numpy as np
import pandas as pd
df = load_wine()

print(df.feature_names) #tributos/colunas
#informar os tipos dos atributos da base de dados
print(df.data.shape) #quantidade de registros e colunas
print(df['data'][:10])#listar as 10 primeiras amostras

"""3. Baixar a base de dados abalone através da ferramenta Panda"""

#from sklearn.datasets import load_abalone
import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data'
attributes = ["Sex", "Length", "Diameter_height", "Whole_weight", "Shucked_weight", "Viscera_weight", "Shell_weight", "Rings"]
abalone = pd.read_csv(url, names = attributes)

print(abalone.count()) #tamanho da base de dados e variaveis existentes

print(abalone.dtypes) #Mostar os tipos de cada atributo